//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://taskmanager.zwiazek.net/soap/Taskmanager/computer", ConfigurationName="ServiceReference1.ComputerPort")]
    public interface ComputerPort {
        
        // CODEGEN: Generating message contract since element name data from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://taskmanager.zwiazek.net/soap/Taskmanager/computer#addInformation", ReplyAction="*")]
        WindowsApp.ServiceReference1.addInformationResponse addInformation(WindowsApp.ServiceReference1.addInformationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://taskmanager.zwiazek.net/soap/Taskmanager/computer#addInformation", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsApp.ServiceReference1.addInformationResponse> addInformationAsync(WindowsApp.ServiceReference1.addInformationRequest request);
        
        // CODEGEN: Generating message contract since element name params from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://taskmanager.zwiazek.net/soap/Taskmanager/computer#getInformation", ReplyAction="*")]
        WindowsApp.ServiceReference1.getInformationResponse getInformation(WindowsApp.ServiceReference1.getInformationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://taskmanager.zwiazek.net/soap/Taskmanager/computer#getInformation", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsApp.ServiceReference1.getInformationResponse> getInformationAsync(WindowsApp.ServiceReference1.getInformationRequest request);
        
        // CODEGEN: Generating message contract since element name getListResult from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://taskmanager.zwiazek.net/soap/Taskmanager/computer#getList", ReplyAction="*")]
        WindowsApp.ServiceReference1.getListResponse getList(WindowsApp.ServiceReference1.getListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://taskmanager.zwiazek.net/soap/Taskmanager/computer#getList", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsApp.ServiceReference1.getListResponse> getListAsync(WindowsApp.ServiceReference1.getListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addInformationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addInformation", Namespace="http://taskmanager.zwiazek.net/soap/Taskmanager/computer", Order=0)]
        public WindowsApp.ServiceReference1.addInformationRequestBody Body;
        
        public addInformationRequest() {
        }
        
        public addInformationRequest(WindowsApp.ServiceReference1.addInformationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class addInformationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string data;
        
        public addInformationRequestBody() {
        }
        
        public addInformationRequestBody(string data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addInformationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addInformationResponse", Namespace="http://taskmanager.zwiazek.net/soap/Taskmanager/computer", Order=0)]
        public WindowsApp.ServiceReference1.addInformationResponseBody Body;
        
        public addInformationResponse() {
        }
        
        public addInformationResponse(WindowsApp.ServiceReference1.addInformationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class addInformationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addInformationResult;
        
        public addInformationResponseBody() {
        }
        
        public addInformationResponseBody(string addInformationResult) {
            this.addInformationResult = addInformationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInformationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInformation", Namespace="http://taskmanager.zwiazek.net/soap/Taskmanager/computer", Order=0)]
        public WindowsApp.ServiceReference1.getInformationRequestBody Body;
        
        public getInformationRequest() {
        }
        
        public getInformationRequest(WindowsApp.ServiceReference1.getInformationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getInformationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @params;
        
        public getInformationRequestBody() {
        }
        
        public getInformationRequestBody(string @params) {
            this.@params = @params;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInformationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInformationResponse", Namespace="http://taskmanager.zwiazek.net/soap/Taskmanager/computer", Order=0)]
        public WindowsApp.ServiceReference1.getInformationResponseBody Body;
        
        public getInformationResponse() {
        }
        
        public getInformationResponse(WindowsApp.ServiceReference1.getInformationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getInformationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getInformationResult;
        
        public getInformationResponseBody() {
        }
        
        public getInformationResponseBody(string getInformationResult) {
            this.getInformationResult = getInformationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getList", Namespace="http://taskmanager.zwiazek.net/soap/Taskmanager/computer", Order=0)]
        public WindowsApp.ServiceReference1.getListRequestBody Body;
        
        public getListRequest() {
        }
        
        public getListRequest(WindowsApp.ServiceReference1.getListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getListRequestBody {
        
        public getListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getListResponse", Namespace="http://taskmanager.zwiazek.net/soap/Taskmanager/computer", Order=0)]
        public WindowsApp.ServiceReference1.getListResponseBody Body;
        
        public getListResponse() {
        }
        
        public getListResponse(WindowsApp.ServiceReference1.getListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getListResult;
        
        public getListResponseBody() {
        }
        
        public getListResponseBody(string getListResult) {
            this.getListResult = getListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ComputerPortChannel : WindowsApp.ServiceReference1.ComputerPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComputerPortClient : System.ServiceModel.ClientBase<WindowsApp.ServiceReference1.ComputerPort>, WindowsApp.ServiceReference1.ComputerPort {
        
        public ComputerPortClient() {
        }
        
        public ComputerPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComputerPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComputerPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComputerPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsApp.ServiceReference1.addInformationResponse WindowsApp.ServiceReference1.ComputerPort.addInformation(WindowsApp.ServiceReference1.addInformationRequest request) {
            return base.Channel.addInformation(request);
        }
        
        public string addInformation(string data) {
            WindowsApp.ServiceReference1.addInformationRequest inValue = new WindowsApp.ServiceReference1.addInformationRequest();
            inValue.Body = new WindowsApp.ServiceReference1.addInformationRequestBody();
            inValue.Body.data = data;
            WindowsApp.ServiceReference1.addInformationResponse retVal = ((WindowsApp.ServiceReference1.ComputerPort)(this)).addInformation(inValue);
            return retVal.Body.addInformationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsApp.ServiceReference1.addInformationResponse> WindowsApp.ServiceReference1.ComputerPort.addInformationAsync(WindowsApp.ServiceReference1.addInformationRequest request) {
            return base.Channel.addInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsApp.ServiceReference1.addInformationResponse> addInformationAsync(string data) {
            WindowsApp.ServiceReference1.addInformationRequest inValue = new WindowsApp.ServiceReference1.addInformationRequest();
            inValue.Body = new WindowsApp.ServiceReference1.addInformationRequestBody();
            inValue.Body.data = data;
            return ((WindowsApp.ServiceReference1.ComputerPort)(this)).addInformationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsApp.ServiceReference1.getInformationResponse WindowsApp.ServiceReference1.ComputerPort.getInformation(WindowsApp.ServiceReference1.getInformationRequest request) {
            return base.Channel.getInformation(request);
        }
        
        public string getInformation(string @params) {
            WindowsApp.ServiceReference1.getInformationRequest inValue = new WindowsApp.ServiceReference1.getInformationRequest();
            inValue.Body = new WindowsApp.ServiceReference1.getInformationRequestBody();
            inValue.Body.@params = @params;
            WindowsApp.ServiceReference1.getInformationResponse retVal = ((WindowsApp.ServiceReference1.ComputerPort)(this)).getInformation(inValue);
            return retVal.Body.getInformationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsApp.ServiceReference1.getInformationResponse> WindowsApp.ServiceReference1.ComputerPort.getInformationAsync(WindowsApp.ServiceReference1.getInformationRequest request) {
            return base.Channel.getInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsApp.ServiceReference1.getInformationResponse> getInformationAsync(string @params) {
            WindowsApp.ServiceReference1.getInformationRequest inValue = new WindowsApp.ServiceReference1.getInformationRequest();
            inValue.Body = new WindowsApp.ServiceReference1.getInformationRequestBody();
            inValue.Body.@params = @params;
            return ((WindowsApp.ServiceReference1.ComputerPort)(this)).getInformationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsApp.ServiceReference1.getListResponse WindowsApp.ServiceReference1.ComputerPort.getList(WindowsApp.ServiceReference1.getListRequest request) {
            return base.Channel.getList(request);
        }
        
        public string getList() {
            WindowsApp.ServiceReference1.getListRequest inValue = new WindowsApp.ServiceReference1.getListRequest();
            inValue.Body = new WindowsApp.ServiceReference1.getListRequestBody();
            WindowsApp.ServiceReference1.getListResponse retVal = ((WindowsApp.ServiceReference1.ComputerPort)(this)).getList(inValue);
            return retVal.Body.getListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsApp.ServiceReference1.getListResponse> WindowsApp.ServiceReference1.ComputerPort.getListAsync(WindowsApp.ServiceReference1.getListRequest request) {
            return base.Channel.getListAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsApp.ServiceReference1.getListResponse> getListAsync() {
            WindowsApp.ServiceReference1.getListRequest inValue = new WindowsApp.ServiceReference1.getListRequest();
            inValue.Body = new WindowsApp.ServiceReference1.getListRequestBody();
            return ((WindowsApp.ServiceReference1.ComputerPort)(this)).getListAsync(inValue);
        }
    }
}
